package com.rinku.csmg.customer.management.model;

import lombok.Data;

/**
 * Clase de salida de la api de roles.
 * 
 * @author Felipe Monzón
 * @since 15 jun. 2021
 * @enterprise Rinku Cinema
 * @version 1.0.0
 */
@Data
public class Rol {
  /**
   * Principal id, generated by sequence
   */
  private Long idRol;
  /**
   * Description of the role.
   */
  private String description;
}
