package com.rinku.csmg.customer.management.entity;

import com.rinku.csmg.customer.management.constant.DatabaseConstant;

import lombok.Data;

import org.hibernate.annotations.NaturalId;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Entity for roles.
 * 
 * @author Felipe Monzón
 * @since 30 may. 2021
 * @enterprise Rinku Cinema
 * @version 1.0.0
 */
@Data
@Entity
@Table(name = DatabaseConstant.ROLES_TABLE)
public class RolEntity {
  /**
   * Principal id, generated by sequence
   */
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = DatabaseConstant.ID_ROL_FIELD, nullable = false, updatable = false)
  private Long idRol;
  /**
   * Description of the role.
   */
  @NaturalId
  @Column(name = DatabaseConstant.DESCRIPTION_FIELD, nullable = false, unique = true, length = 50)
  private String description;
  /**
   * Salario del empleado.
   */
  @Column(name = DatabaseConstant.SALARY_FIELD, nullable = false)
  private BigDecimal salary;
}
